<?php include THEME_PATH . DS . 'header.phtml'; ?>

<form class="form-signin text-center" method="POST">
    <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

    <label for="username" class="sr-only">Username</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>

    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Connexion</button>
    <p class="mt-5 mb-3 text-muted">&copy; <?= date('Y') ?></p>
</form>

<?php include THEME_PATH . DS . 'footer.phtml'; ?>

