
<nav class="navbar navbar-expand-lg navbar-light bg-light container-fluid">
    <a class="navbar-brand" href="<?= BASE_URL ?>">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse container-fluid" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <?php if(isset($_SESSION['user'])) : ?>
            <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-user-astronaut"></i> <?= ucfirst($_SESSION['user']['username']) ;?>
     </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fa fa-user-circle"></i> Préference</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-cog "></i> Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="logout.php"><i class="fa fa-sign-out-alt"></i> Déconnexion</a>
                </div>
            </li>
            <?php else : ?>
            <li class="nav-item">
                <a class="dropdown-item" href="login.php"><i class="fa fa-user-astronaut"></i> Connexion</a>
            </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>