
<nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid">
    <a href="<?= BASE_URL ?>"><img src="<?= BASE_URL ?>/img/logo.png" height="20px" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse container-fluid" id="navbarNav">
        <ul class="navbar-nav">

            <?php if(isset($_SESSION['user'])) : ?>

                <li class="nav-item">
                    <a class="nav-link" href="<?= BASE_URL ?>/dashboard">Dashboard</a>
                </li>
                <li class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Blog
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="<?= BASE_URL ?>/blog.php">Tous les articles</a>
                        <a class="dropdown-item" href="<?= BASE_URL ?>/blog/mes-articles.php"> Mes articles</a>
                        <a class="dropdown-item" href="<?= BASE_URL ?>/blog/add-article.php"> Ajouter un article</a>
                    </div>
                </li>

            <?php else : ?>

                <li class="nav-item">
                    <a class="nav-link" href="<?= BASE_URL ?>/blog.php">Blog</a>
                </li>

            <?php endif; ?>

        </ul>
        <ul class="navbar-nav">

            <?php if(isset($_SESSION['user'])) : ?>

            <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-user-astronaut"></i> <?= ucfirst($_SESSION['user']['username']) ;?>
     </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="#"><i class="fa fa-user-circle"></i> Préference</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-cog "></i> Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="<?= BASE_URL ?>/logout.php"><i class="fa fa-sign-out-alt"></i> Déconnexion</a>
                </div>
            </li>

            <?php else : ?>

            <li class="nav-item">
                <a class="dropdown-item btn btn-default" href="<?= BASE_URL ?>/login.php"><i class="fa fa-user-astronaut"></i> Connexion</a>
            </li>

            <?php endif; ?>

        </ul>
    </div>
</nav>